---
title: "Quetelet's Body Mass Index"
author: "coop711"
date: "2015년 3월 9일"
output: html_document
---

`rn96.txt` 자료 읽어들이고, 기초통계 요약하기
---------------------------------------

- `rn96.txt` 자료 읽어들이기, 원 자료를 보고 `header` 매개변수 추가

```{r}
rn96<-read.table("rn96.txt",header=TRUE)
```

- `rn96` 의 자료구조 살피기. 

```{r}
str(rn96)
```
- `height` 와 `weight` 의 기초통계 살피기

```{r}
summary(rn96)
```

- 평균과 표준편차만 살펴보려면

```{r}
apply(rn96,2,mean)
apply(rn96,2,sd)
```
---

---

- `height` 와 `weight` 의 산점도 그리기

```{r fig.width=4, fig.height=4}
plot(weight~height, data=rn96)
```

- 선형회귀선 추가하기

```{r fig.width=4, fig.height=4}
plot(weight~height, data=rn96)
abline(lm(weight~height, data=rn96)$coefficient)
```

- 선형모형으로 분석하기

```{r}
rn96.lm<-lm(weight~height, data=rn96)
```

- 회귀계수와 관련 통계량 살피기

```{r}
summary(rn96.lm)
```

- `lowess` local smoother 추가하기

```{r fig.width=4, fig.height=4}
plot(weight~height, data=rn96)
abline(lm(weight~height, data=rn96)$coefficient)
lines(lowess(rn96$height,rn96$weight),col="red")
```


BMI 계산하고 줄기-잎 그리기
---------------------------

- 조금 편하게 작업하기 위해서

```{r}
attach(rn96)
search()
```

- BMI 공식은 $\frac{몸무게(kg)}{키^2(m)}$

```{r}
BMI<-round(weight/(height/100)^2,digits=1)
head(cbind(rn96, BMI))
```

- BMI 값들의 줄기-잎 그림 그리기

```{r}
stem(BMI)
```

---

---

---

---

---

---

---

---

---

- 조금더 알아보기 쉽게 매개변수를 바꾸기

```{r}
stem(BMI,scale=2)
```

- 각 변수는정규분포에 가까울까?

```{r fig.width=5, fig.height=5}
qqnorm(weight)
```

```{r fig.width=4.5, fig.height=4.5}
qqnorm(height)
```

```{r fig.width=4.5, fig.height=4.5}
qqnorm(BMI)
```

- `weight`와 `height`의 줄기-잎 그림

```{r}
stem(weight)
stem(height)
```

R base package 에서 제공하는 정규성 테스트
------------------------------------------

- Shapiro-Wilk test, `shapiro.test()`

```{r}
shapiro.test(weight)
shapiro.test(height)
shapiro.test(BMI)
```
- Kolmogorov-Smirnov test, `ks.test()`

```{r}
ks.test(weight, "pnorm", mean=mean(weight), sd=sd(weight))
ks.test(height, "pnorm", mean=mean(height), sd=sd(height))
ks.test(BMI, "pnorm", mean=mean(BMI), sd=sd(BMI))
```